### ISSUE TITLE
Documentation; no mention of ATSC zap format

### ISSUE THREAD

**Issue by oviano** [tsduck/tsduck#214] opened 2019-02-03 20:29 UTC
On page 122 of the User's Guide it describes the zap string format for Satellite, Cable and Terrestrial but I think in this context Terrestrial only means DVB-T/T2 as it only describes that format.

Does this mean that the ATSC "azap" format is not supported, or is it just missing from the documentation?

The correct format for ATSC seems to be quite simple:

freq:mod

Reference:
https://www.linuxtv.org/wiki/index.php/Dvbscan

**Comment by lelegard** [comment] 2019-02-03 22:34
As mentioned in #211, the zap format was used at the very beginning of TSDuck. At that time, there was no `azap` and there is not ATSC zap format in TSDuck.

Although this issue is not a true duplicate of #211, it is included in #211: if the zap format has sufficiently evolved in the Linux community, TSDuck will include all current features (including ATSC if there is one). Otherwise, it will be dropped.

I close this issue and let further discussion in #211.

**Closed by lelegard** 2019-02-03 22:34 UTC
